package com.github.jozephineg.model.enums;

// To be added when refactoring code
public enum Constituent {

    BLEKINGELÄN,
    DALARNASLÄN,
    GOTLANDSLÄN,
    GÄVLEBORGSLÄN,
    GÖTEBORGSKOMMUN,
    HALLANDSLÄN,
    JÄMTLANDSLÄN,
    JÖNKÖPINGSLÄN,
    KALMARLÄN,
    KRONOBERGSLÄN,
    MALMÖKOMMUN,
    NORRBOTTENSLÄN,
    SKÅNELÄNNORRASÖDRA,
    SKÅNELÄNSÖDRA,
    SKÅNELÄNVÄSTRA,
    STOCKHOLMSKOMMUN,
    STOCKHOLMSLÄN,
    SÖDERMANLANDSLÄN,
    UPPSALALÄN,
    VÄRMLANDSLÄN,
    VÄSTERBOTTENSLÄN,
    VÄSTERNORRLANDSLÄN,
    VÄSTMANLANDSLÄN,
    VÄSTRAGÖTALANDSLÄNNORRA,
    VÄSTRAGÖTALANDSLÄNSÖDRA,
    VÄSTRAGÖTALANDSLÄNVÄSTRA,
    VÄSTRAGÖTALANDSLÄNÖSTRA,
    ÖREBROLÄN,
    ÖSTERGÖTLANDSLÄN,

}
