version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment:
    - discovery.zen.minimum_master_nodes=1
    - discovery.type=single-node
    - xpack.security.enabled=false
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local